### ISSUE TITLE
Does this example work with XCode Preview?

### ISSUE THREAD

**Issue by Artein** [DavidPeicho/unity-swiftui-example#8]
One of the greatest features of SwiftUI is to receive almost immediate response to changes via XCode Preview.
Does the combination of Unity with SwiftUI work in XCode Preview?

**Comment by Artein** [comment]
Thank you, @DavidPeicho . Please, let me know if you will find the way. For fine-tuning of UI, it is a great feature.

For now, I found an additional workaround (without #if's and so on), to just compile to my Mac as an app designed for iPhone. Everything works as expected and super fast (at least on my MacBook Pro 2021 with M1 Pro)
<img width="247" alt="Screenshot 2022-02-04 at 10 16 25" src="https://user-images.githubusercontent.com/1109722/152494926-981f1b4a-8f2a-4a32-bd7a-b4ec4e5135ae.png">

**Comment by DavidPeicho** [comment]
Yes that's a good idea!

TBH I didn't try to work on that because:
* if I need to debug Unity code, I do it in Unity.
* If I need to run UI stuff, I only use the simulator (and then I strip away the Unity code conditionnally).

If really I need to see the entire app running together, I run it on phone. We have a large app (500mB) and building on iPhoneX takes 2-3s on Macbook Pro 16 (obviously when re-building, not for an initial cold build).
